# Generated by Django 2.0.8 on 2018-08-11 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20180811_1750'),
        ('courses', '0003_auto_20180811_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='organization.CourseOrg', verbose_name='所属机构'),
        ),
    ]
