# Generated by Django 2.0.8 on 2018-08-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180813_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tag',
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='courses', to='courses.Tag', verbose_name='课程标签'),
        ),
    ]
