# Generated by Django 2.0.8 on 2018-08-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20180813_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='访问地址'),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(related_name='courses', to='courses.Tag', verbose_name='课程标签'),
        ),
    ]
