# Generated by Django 2.0.8 on 2018-08-13 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='notes',
            field=models.CharField(default='', max_length=20, verbose_name='课程须知'),
        ),
        migrations.AddField(
            model_name='course',
            name='tell_you',
            field=models.CharField(default='', max_length=20, verbose_name='讲师告诉你学到了什么'),
        ),
    ]
