# Generated by Django 2.0.8 on 2018-08-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180811_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='image/default.jpg', null=True, upload_to='image/%Y/%m', verbose_name='头像'),
        ),
    ]
